version: '3.8'

services:
  app:
    build: .
    container_name: scholacbt-app
    restart: always
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      - CI_ENV=production
      - DB_HOST=db
      - DB_USERNAME=scholacbt_user
      - DB_PASSWORD=scholacbt_password
      - DB_DATABASE=scholacbt_db
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: scholacbt-db
    restart: always
    environment:
      - MYSQL_DATABASE=scholacbt_db
      - MYSQL_USER=scholacbt_user
      - MYSQL_PASSWORD=scholacbt_password
      - MYSQL_ROOT_PASSWORD=scholacbt_root_password
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  db_data:
